#!/bin/bash

if [ "$1" == "-v" ]
then
  shift
  mvn exec:java -Dexec.mainClass=eu.monnetproject.coal.CoalAligner -Dexec.args="$*"
else
  mvn -q -f main/pom.xml exec:java -Dexec.mainClass=eu.monnetproject.coal.CoalAligner -Dexec.args="$*"
fi
